"""Shared PDF Generation Pipeline — Jinja2 → Playwright → PDF.

Single pipeline for all three document types (Prescription, Invoice, Certificate).
Each type has a Jinja2 template with clinic letterhead, inline Tailwind CSS,
and a shared Playwright rendering step.

Usage:
    from app.services.pdf_generator import PDFGenerator
    pdf = PDFGenerator()
    path = await pdf.generate_prescription(data)
    path = await pdf.generate_invoice(data)
    path = await pdf.generate_certificate(data, cert_type="sick_leave")
"""

from __future__ import annotations

import os
import uuid
import logging
from datetime import datetime, timezone
from typing import Any, Dict, Optional
from jinja2 import Environment, BaseLoader, TemplateNotFound
from playwright.async_api import async_playwright

logger = logging.getLogger(__name__)

OUTPUT_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "outputs", "pdfs")

CLINIC_DEFAULTS = {
    "clinic_name": "SoloPrac Clinic",
    "clinic_address": "Aundh, Pune, Maharashtra",
    "clinic_phone": "+91-9876543210",
    "clinic_email": "clinic@soloprac.ai",
    "doctor_name": "Dr. Rohan Bhoge",
    "registration_number": "MH-12345",
}

# ─── Jinja2 Templates (inline) ─────────────────────

PRESCRIPTION_TEMPLATE = """<!DOCTYPE html>
<html><head><meta charset="utf-8"><style>
  body { font-family: 'Inter', Arial, sans-serif; font-size: 11pt; line-height: 1.4; margin: 0; padding: 20px; color: #1a1a1a; }
  .letterhead { text-align: center; border-bottom: 2px solid #2563eb; padding-bottom: 8px; margin-bottom: 16px; }
  .letterhead .name { font-size: 16pt; font-weight: bold; color: #1e40af; }
  .letterhead .details { font-size: 8pt; color: #64748b; }
  .header { display: flex; justify-content: space-between; margin-bottom: 12px; font-size: 9pt; }
  .rx-box { border: 2px solid #eab308; background: #fffbeb; padding: 16px; border-radius: 8px; margin: 12px 0; }
  .rx-box h3 { margin: 0 0 8px 0; font-size: 10pt; color: #92400e; }
  table { width: 100%; border-collapse: collapse; font-size: 9pt; }
  table th { background: #f1f5f9; text-align: left; padding: 4px 6px; border-bottom: 1px solid #e2e8f0; }
  table td { padding: 4px 6px; border-bottom: 1px solid #f1f5f9; }
  .warning-pill { display: inline-block; background: #fef2f2; color: #dc2626; padding: 1px 6px; border-radius: 4px; font-size: 8pt; }
  .footer { margin-top: 20px; font-size: 8pt; color: #94a3b8; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 8px; }
  .disclaimer { font-size: 7pt; color: #94a3b8; text-align: center; margin-top: 4px; font-style: italic; }
</style></head><body>
<div class="letterhead">
  <div class="name">{{ clinic.clinic_name }}</div>
  <div class="details">{{ clinic.clinic_address }} | {{ clinic.clinic_phone }} | {{ clinic.clinic_email }}</div>
</div>
<div class="header">
  <div><strong>Patient:</strong> {{ patient_name }}<br><strong>Age/Sex:</strong> {{ patient_age }}/{{ patient_gender }}<br><strong>Date:</strong> {{ date }}</div>
  <div><strong>Doctor:</strong> {{ clinic.doctor_name }}<br><strong>Reg No:</strong> {{ clinic.registration_number }}</div>
</div>
<div class="rx-box">
  <h3>Prescription</h3>
  {% if diagnosis %}<p><strong>Diagnosis:</strong> {{ diagnosis }}</p>{% endif %}
  <table><tr><th>#</th><th>Drug</th><th>Strength</th><th>Dose</th><th>Frequency</th><th>Duration</th></tr>
  {% for med in medications %}
  <tr><td>{{ loop.index }}</td><td>{{ med.drug }}</td><td>{{ med.strength }}</td><td>{{ med.dose }}</td><td>{{ med.frequency }}</td><td>{{ med.duration }}</td></tr>
  {% endfor %}
  </table>
  {% if instructions %}<p style="margin-top:8px;"><strong>Instructions:</strong> {{ instructions }}</p>{% endif %}
  {% if follow_up %}<p><strong>Follow-up:</strong> {{ follow_up }}</p>{% endif %}
</div>
<div class="footer">This is an AI-assisted draft — validated by Dr. {{ clinic.doctor_name }}. Not a substitute for clinical judgement.</div>
<div class="disclaimer">AI Suggestion — Requires Doctor Validation. Generated by SoloPrac AI on {{ now }}.</div>
</body></html>"""

INVOICE_TEMPLATE = """<!DOCTYPE html>
<html><head><meta charset="utf-8"><style>
  body { font-family: 'Inter', Arial, sans-serif; font-size: 11pt; margin: 0; padding: 20px; color: #1a1a1a; }
  .letterhead { text-align: center; border-bottom: 2px solid #2563eb; padding-bottom: 8px; margin-bottom: 16px; }
  .letterhead .name { font-size: 16pt; font-weight: bold; color: #1e40af; }
  .letterhead .details { font-size: 8pt; color: #64748b; }
  .header { display: flex; justify-content: space-between; margin-bottom: 12px; font-size: 9pt; }
  .inv-no { font-size: 12pt; font-weight: bold; color: #1e40af; margin-bottom: 8px; }
  table { width: 100%; border-collapse: collapse; font-size: 9pt; }
  table th { background: #f1f5f9; text-align: left; padding: 6px; border-bottom: 2px solid #2563eb; }
  table td { padding: 6px; border-bottom: 1px solid #e2e8f0; }
  .totals { margin-top: 8px; text-align: right; font-size: 10pt; }
  .totals .total { font-size: 14pt; font-weight: bold; color: #1e40af; }
  .status-badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 8pt; font-weight: bold; }
  .status-paid { background: #dcfce7; color: #16a34a; }
  .status-pending { background: #fef9c3; color: #ca8a04; }
  .footer { margin-top: 20px; font-size: 8pt; color: #94a3b8; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 8px; }
</style></head><body>
<div class="letterhead">
  <div class="name">{{ clinic.clinic_name }}</div>
  <div class="details">{{ clinic.clinic_address }} | {{ clinic.clinic_phone }} | {{ clinic.clinic_email }}</div>
</div>
<div class="inv-no">Invoice: {{ invoice_number }}</div>
<div class="header">
  <div><strong>Patient:</strong> {{ patient_name }}<br><strong>Date:</strong> {{ date }}</div>
  <div><strong>Status:</strong> <span class="status-badge status-{{ status }}">{{ status|upper }}</span></div>
</div>
<table><tr><th>#</th><th>Description</th><th>Qty</th><th>Rate</th><th>Amount</th></tr>
{% for item in items %}
<tr><td>{{ loop.index }}</td><td>{{ item.description }}</td><td>{{ item.qty }}</td><td>{{ item.rate }}</td><td>{{ item.amount }}</td></tr>
{% endfor %}
</table>
<div class="totals">
  <p>Subtotal: {{ subtotal }}</p>
  {% if tax %}<p>Tax: {{ tax }}</p>{% endif %}
  <p class="total">Total: {{ total }}</p>
</div>
{% if notes %}<p style="font-size:9pt;margin-top:8px;"><strong>Notes:</strong> {{ notes }}</p>{% endif %}
<div class="footer">Generated by SoloPrac AI on {{ now }}. Thank you for your visit.</div>
<div class="disclaimer" style="font-size:7pt;color:#94a3b8;text-align:center;font-style:italic;">AI Suggestion — Requires Doctor Validation.</div>
</body></html>"""

CERTIFICATE_TEMPLATE = """<!DOCTYPE html>
<html><head><meta charset="utf-8"><style>
  body { font-family: 'Inter', Arial, sans-serif; font-size: 11pt; margin: 0; padding: 20px; color: #1a1a1a; }
  .letterhead { text-align: center; border-bottom: 2px solid #2563eb; padding-bottom: 8px; margin-bottom: 16px; }
  .letterhead .name { font-size: 16pt; font-weight: bold; color: #1e40af; }
  .letterhead .details { font-size: 8pt; color: #64748b; }
  h2 { text-align: center; color: #1e40af; font-size: 14pt; margin: 16px 0; }
  .content { margin: 16px 0; line-height: 1.6; font-size: 10pt; }
  .qr { text-align: center; margin: 16px 0; }
  .qr img { width: 80px; height: 80px; }
  .verify { text-align: center; font-size: 8pt; color: #64748b; }
  .footer { margin-top: 20px; font-size: 8pt; color: #94a3b8; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 8px; }
</style></head><body>
<div class="letterhead">
  <div class="name">{{ clinic.clinic_name }}</div>
  <div class="details">{{ clinic.clinic_address }} | {{ clinic.clinic_phone }} | {{ clinic.clinic_email }}</div>
</div>
<h2>Medical Certificate</h2>
<p style="text-align:center;font-size:9pt;color:#64748b;">{{ cert_type | replace('_', ' ') | title }}</p>
<div class="content">
  <p><strong>Patient:</strong> {{ patient_name }}</p>
  <p><strong>Date:</strong> {{ date }}</p>
  <p><strong>This is to certify that</strong> {{ patient_name }} {% if patient_age %} ({{ patient_age }} years) {% endif %} is under my medical care.</p>
  {% if body %}<p>{{ body }}</p>{% endif %}
  {% if recommended_rest %}<p><strong>Recommended rest:</strong> {{ recommended_rest }}</p>{% endif %}
</div>
<div class="qr">
  {% if verification_code %}<p style="font-size:9pt;">Verification Code: <strong>{{ verification_code }}</strong></p>{% endif %}
  <p class="verify">Verify at: {{ verify_url }}</p>
</div>
<div style="margin-top:24px;text-align:right;">
  <p>{{ clinic.doctor_name }}</p>
  <p style="font-size:9pt;color:#64748b;">{{ clinic.registration_number }}</p>
  <p style="font-size:9pt;color:#64748b;">{{ clinic.clinic_name }}</p>
</div>
<div class="footer">Generated by SoloPrac AI on {{ now }}. This is a computer-generated certificate.</div>
<div class="disclaimer" style="font-size:7pt;color:#94a3b8;text-align:center;font-style:italic;">AI Suggestion — Requires Doctor Validation.</div>
</body></html>"""


# ─── Template Loader ────────────────────────────────

class _InlineLoader(BaseLoader):
    def __init__(self):
        self.templates = {
            "prescription": PRESCRIPTION_TEMPLATE,
            "invoice": INVOICE_TEMPLATE,
            "certificate": CERTIFICATE_TEMPLATE,
        }

    def get_source(self, environment, template):
        if template in self.templates:
            return self.templates[template], template, True
        raise TemplateNotFound(template)


_jinja_env = Environment(loader=_InlineLoader(), autoescape=True)


# ─── PDF Generator ──────────────────────────────────

class PDFGenerator:
    """Shared Jinja2 → Playwright → PDF generation for all document types."""

    def __init__(self, output_dir: Optional[str] = None):
        self.output_dir = output_dir or OUTPUT_DIR
        os.makedirs(self.output_dir, exist_ok=True)

    def _prepare_context(self, data: Dict[str, Any]) -> Dict[str, Any]:
        """Merge clinic defaults into the template context."""
        context = dict(CLINIC_DEFAULTS)
        context.update(data)
        context["now"] = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        # Format monetary values with ₹ symbol
        for key in ["subtotal", "total", "tax"]:
            if key in context and isinstance(context[key], (int, float)):
                context[key] = f"₹{context[key]:,.2f}"
        return context

    async def _render_to_pdf(self, template_name: str, context: Dict[str, Any], output_path: str) -> str:
        """Render Jinja2 template → HTML → Playwright → PDF."""
        template = _jinja_env.get_template(template_name)
        html = template.render(**context)

        async with async_playwright() as p:
            browser = await p.chromium.launch()
            page = await browser.new_page()
            await page.set_content(html, wait_until="networkidle")
            await page.pdf(path=output_path, format="A5", margin={"top": "10mm", "bottom": "10mm", "left": "10mm", "right": "10mm"})
            await browser.close()

        logger.info("PDF generated: %s (%s)", output_path, template_name)
        return output_path

    # ─── Prescription ───

    async def generate_prescription(
        self,
        patient_name: str,
        patient_age: int = 0,
        patient_gender: str = "",
        date: str = "",
        diagnosis: str = "",
        medications: list = None,
        instructions: str = "",
        follow_up: str = "",
        doctor_name: str = "",
    ) -> str:
        filename = f"rx_{uuid.uuid4().hex[:12]}.pdf"
        path = os.path.join(self.output_dir, filename)
        context = self._prepare_context({
            "patient_name": patient_name, "patient_age": patient_age,
            "patient_gender": patient_gender, "date": date or datetime.now(timezone.utc).strftime("%Y-%m-%d"),
            "diagnosis": diagnosis, "medications": medications or [], "instructions": instructions, "follow_up": follow_up,
        })
        if doctor_name:
            context["clinic"] = dict(CLINIC_DEFAULTS)
            context["clinic"]["doctor_name"] = doctor_name
        return await self._render_to_pdf("prescription", context, path)

    # ─── Invoice ───

    async def generate_invoice(
        self,
        patient_name: str,
        invoice_number: str,
        date: str = "",
        items: list = None,
        subtotal: float = 0.0,
        tax: float = 0.0,
        total: float = 0.0,
        status: str = "pending",
        notes: str = "",
    ) -> str:
        filename = f"inv_{uuid.uuid4().hex[:12]}.pdf"
        path = os.path.join(self.output_dir, filename)
        context = self._prepare_context({
            "patient_name": patient_name, "invoice_number": invoice_number,
            "date": date or datetime.now(timezone.utc).strftime("%Y-%m-%d"),
            "items": items or [], "subtotal": subtotal, "tax": tax, "total": total, "status": status, "notes": notes,
        })
        return await self._render_to_pdf("invoice", context, path)

    # ─── Certificate ───

    async def generate_certificate(
        self,
        patient_name: str,
        patient_age: int = 0,
        cert_type: str = "sick_leave",
        body: str = "",
        recommended_rest: str = "",
        verification_code: str = "",
        verify_url: str = "",
        date: str = "",
    ) -> str:
        filename = f"cert_{uuid.uuid4().hex[:12]}.pdf"
        path = os.path.join(self.output_dir, filename)
        context = self._prepare_context({
            "patient_name": patient_name, "patient_age": patient_age, "cert_type": cert_type,
            "body": body, "recommended_rest": recommended_rest,
            "verification_code": verification_code, "verify_url": verify_url,
            "date": date or datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        })
        return await self._render_to_pdf("certificate", context, path)


pdf_generator = PDFGenerator()
